on:
  workflow_call:

jobs:
  common-action1:
    runs-on: ubuntu:latest
    steps:
    - name: Checkout main
      id: checkout_release
      uses: actions/checkout@v3
  common-action2:
    runs-on: ubuntu:latest
    needs: [common-action1]
    concurrency:
      group: test-group
    steps:
    - name: sleeping
      id: sleeping_id
      shell: bash
      run: |
        echo "Hello World"
        sleep 1m